#pragma once
#include <string>
#include <filesystem>

enum class ERROR {
    ILEGAL_CHARACTER,
    ILEGAL_IDENTIFIER,
    MISSING_BECOMES,
    MISSING_DO,
    MISSING_STATEMENT,
    MISSING_ELSE,
    EXPECTING_PROGRAM,
    EXPECTING_SEMICOLON,
    EXPECTING_BEGIN,
    EXPECTING_END,
    EXPECTING_CONST,
    EXPECTING_IDENTIFIER,
    EXPECTING_INTEGER,
    EXPECTING_LPAREN,
    EXPECTING_RPAREN,
    EXPECTING_STATEMENT,
    EXPECTING_OPERATOR,
    EXPECTING_ODD,
    EXPECTING_EXPR,
    EXPECTING_DO,
    EXPECTING_THEN,
    EXPECTING_FACTOR,
    EXPECTING_PROCEDURE,
    EXPECTING_VAR_CONST_INTEGER,
    MISSING_SEMICOLON,
    MISSING_COMMA,
    MISSING_IDENTIFIER,
    MISSING_INTEGER,
    MISSING_OPERATOR,
    MISSING_LEXPR,
    MISSING_EXPR,
    MISSING_LPAREN,
    MISSING_RPAREN,
    MISSING_THEN,
    MISSING_COLON,
    MISSING_BEGIN,
    MISSING_FACTOR,
    OUT_OF_RANGE,
    UNEXPECTED_TOKEN,
    UNDECLARED_IDENTIFIER,
    REDEFINITION_OF_IDENTIFIER,
    REDEFINITION_OF_PROCEDURE,
    EXCEED_MAX_NEST_LEVEL,
    ASSIGN_FOR_CONSTANT,
    INCORRECT_PARAMETERS
};

class Error {
private:
public:
    int ErrCnt;
    Error():ErrCnt(0){}
    void ProcError(ERROR etype, int row, int col, const std::string& token, const std::string& line, const std::string& path);
    void ProcError(ERROR etype, int real, int expected);
};

std::string toString(ERROR eType);